name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x RecipeNotebook/gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: RecipeNotebook

      - name: Test with Gradle Wrapper
        run: ./gradlew test --info
        working-directory: RecipeNotebook

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: RecipeNotebook/build/reports/tests/test/

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-logs
          path: RecipeNotebook/build/test-results/test/

      - name: Run Spring Boot to serve API docs
        run: ./gradlew bootRun &
        working-directory: RecipeNotebook

      - name: Wait for the application to start
        run: sleep 15

      - name: Download OpenAPI spec
        run: curl -o RecipeNotebook/openapi.json http://localhost:8080/v3/api-docs

      - name: Generate OpenAPI HTML
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.10.0/openapi-generator-cli-7.10.0.jar -O openapi-generator-cli.jar
          java -jar openapi-generator-cli.jar generate -i RecipeNotebook/openapi.json -g swagger-ui-single-page -o RecipeNotebook/openapi-docs

      - name: Upload OpenAPI HTML
        uses: actions/upload-artifact@v4
        with:
          name: openapi-html
          path: RecipeNotebook/openapi-docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: RecipeNotebook/openapi-docs
          branch: gh-pages